global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flask"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:5000"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
